const cartActionType={
    TOGGLE_HIDDEN:"TOGGLE_HIDDEN",
    SET_CART_ITEMS_START:"SET_CART_ITEMS_START",
    SET_CART_ITEMS_SUCESS:"SET_CART_ITEMS_SUCESS",
    CLEAR_CART_ITEMS:"CLEAR_CART_ITEMS",
    ADD_ITEM_TO_CART_START:"ADD_ITEM_TO_CART_START",
    ADD_ITEM_TO_CART_SUCCESS:"ADD_ITEM_TO_CART_SUCCESS",
    DELETE_ITEM_FROM_CART_START:"DELETE_ITEM_FROM_CART_START",
    DELETE_ITEM_FROM_CART_SUCCESS:"DELETE_ITEM_FROM_CART_SUCCESS",
    UPDATE_ITEM_IN_CART_START:"UPDATE_ITEM_IN_CART_START",
    UPDATE_ITEM_IN_CART_SUCCESS:"UPDATE_ITEM_IN_CART_SUCCESS"
};
export default cartActionType;