const customerActionType= {
SET_CUSTOMER_TOKEN:"SET_CUSTOMER_TOKEN",
CLEAR_CUSTOMER_TOKEN:"CLEAR_CUSTOMER_TOKEN",
SIGN_IN_START:"SIGN_IN_START",
SIGN_OUT_START:"SIGN_OUT_START",
SIGN_UP_START:"SIGN_UP_START",
SET_ERROR:'SET_ERROR',

};

export default customerActionType;