const guestActionType= {

    SET_CART_ID:"SET_CART_ID",
    CLEAR_CART_ID:"CLEAR_CART_ID",
    GUEST_ADD_ITEM_TO_CART_START:"GUEST_ADD_ITEM_TO_CART_START",
    GUEST_DELETE_ITEM_FROM_CART_START:"GUEST_DELETE_ITEM_FROM_CART_START",
    GUEST_UPDATE_ITEM_To_CART_START:"GUEST_UPDATE_ITEM_To_CART_START",
    SET_GUEST_CART_ITEMS_START:"SET_GUEST_CART_ITEMS_START",
    SET_GUEST_TOTLAS_START:"SET_GUEST_TOTLAS_START" 
    
    };
    
    export default guestActionType;